##
#  oooooooooo.                                                        o8o            ooo        ooooo   .oooooo.   ooooooooooooo oooooooooo.
#  `888'   `Y8b                                                       `"'            `88.       .888'  d8P'  `Y8b  8'   888   `8 `888'   `Y8b
#   888      888 oooo    ooo ooo. .oo.    .oooo.   ooo. .oo.  .oo.   oooo   .ooooo.   888b     d'888  888      888      888       888      888
#   888      888  `88.  .8'  `888P"Y88b  `P  )88b  `888P"Y88bP"Y88b  `888  d88' `"Y8  8 Y88. .P  888  888      888      888       888      888
#   888      888   `88..8'    888   888   .oP"888   888   888   888   888  888        8  `888'   888  888      888      888       888      888
#   888     d88'    `888'     888   888  d8(  888   888   888   888   888  888   .o8  8    Y     888  `88b    d88'      888       888     d88'
#  o888bood8P'       .8'     o888o o888o `Y888""8o o888o o888o o888o o888o `Y8bod8P' o8o        o888o  `Y8bood8P'      o888o     o888bood8P'
#                .o..P'
#                `Y8P'
##
name: DynamicMOTD
main: Kronnosy\DynamicMOTD\DynamicMOTD

api: 5.0.0
version: 1.0.0

author: "Kronnosy"
website: "https://github.com/Kronnosy"
description: "Dynamically shuffles and updates the MOTD for your Minecraft server."
